# Add these to your existing application.yml file

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

# Server configuration
server:
  port: 8081

# Custom file storage configuration
file:
  upload-dir: uploads